services:

  app:
    command:
      - /bin/sh
      - -c
      - |
        python manage.py runserver 0.0.0.0:9000
    environment:
      DEBUG: 'true'
    volumes:
      - .:/code
    depends_on:
      frontend-builder:
        condition: service_completed_successfully

  frontend-builder:
    image: node:19.4.0
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run build
    working_dir: /app
    volumes:
      - ./app:/app