services:

  db:
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres

  app:
    command:
      - /bin/sh
      - -c
      - |
        python manage.py runserver 0.0.0.0:9000
    environment:
      DEBUG : 'TRUE'
      DJANGO_SECRET_KEY : WOOOOOOOOWOOOOOOOOWWW
      POSTGRES_HOST : db
      POSTGRES_PASSWORD : postgres
      POSTGRES_DB : postgres
      POSTGRES_USER : postgres
    volumes:
      - .:/code
    ports:
      - 9000:9000

  celery:
    environment:
      DEBUG : 'TRUE'
      DJANGO_SECRET_KEY : WOOOOOOOOWOOOOOOOOWWW
      POSTGRES_HOST : db
      POSTGRES_PASSWORD : postgres
      POSTGRES_DB : postgres
      POSTGRES_USER : postgres
    volumes:
      - .:/code

  db_init:
    command:
      - /bin/sh
      - -c
      - |
        python manage.py makemigrations api
        python manage.py migrate
        python manage.py createsuperuser --noinput || true
    volumes:
      - .:/code
    environment:
      DEBUG : 'TRUE'
      DJANGO_SECRET_KEY : WOOOOOOOOWOOOOOOOOWWW
      POSTGRES_HOST : db
      POSTGRES_PASSWORD : postgres
      POSTGRES_DB : postgres
      POSTGRES_USER : postgres
      DJANGO_SUPERUSER_USERNAME : admin
      DJANGO_SUPERUSER_PASSWORD : password
      DJANGO_SUPERUSER_EMAIL : admin@example.com

