services:

  app:
    command:
      - /bin/sh
      - -c
      - |
        python manage.py runserver 0.0.0.0:9000
    environment:
      DEBUG: 'true'
    volumes:
      - .:/code
    depends_on:
      frontend-builder:
        condition: service_completed_successfully

