services:
  db:
    volumes:
      - youtube_downloader_db:/var/lib/postgresql/data

  app:
    environment:
      DEBUG: 'true'

volumes:
  youtube_downloader_db:
    external: true
  youtube_downloader:
    external: true