version: '3.8'

services:
  webdb:
    image: postgres:alpine
    volumes:
      - dataweb:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=webdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres

  app:
    command:
      - /bin/sh
      - -c
      - |
        python manage.py runserver 0.0.0.0:9001
      # (cd app && npm install)
      # (cd app && npm run build)
    image: playlistenerweb
    build:
      context: .
      args:
        - VERSION=1.0.0
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - PLAPI_PATH=playlistenerapi:8000
      - DJANGO_SECRET_KEY=WOOOOOOOOWOOOOOOOOWWW
      - POSTGRES_HOST=webdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - webdb

  # frontend-builder:




  
# FROM node:lts-alpine as webassets-builder

# WORKDIR /app

# COPY app .
# RUN npm install
# RUN npm run build



volumes:
  dataweb:

