version: '3.8'

services:
  webdb:
    image: postgres:alpine
    volumes:
      - dataweb:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=webdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    networks:
      playlistener-network:   

  app:
    command: python manage.py runserver 0.0.0.0:9001
    image: playlistenerweb
    build:
      context: .
      args:
        - VERSION=1.0.0
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - PLAPI_PATH=playlistenerapi:8000
      - DJANGO_SECRET_KEY=WOOOOOOOOWOOOOOOOOWWW
      - POSTGRES_HOST=webdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - webdb
    networks:
      playlistener-network:

volumes:
  dataweb:

networks:
  playlistener-network:
    external: true
    driver: bridge
    name: playlistener-network
