# Generated by Django 4.2.13 on 2024-07-20 16:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('youtube_id', models.TextField(max_length=200, unique=True)),
                ('title', models.TextField(blank=True, default='N/A', max_length=200, null=True)),
                ('url', models.TextField(blank=True, max_length=500, null=True)),
                ('audiofile', models.FileField(blank=True, max_length=200, null=True, upload_to=api.models.file_directory_path)),
                ('videofile', models.FileField(blank=True, max_length=200, null=True, upload_to=api.models.file_directory_path)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('QUEUED', 'Queued'), ('BUSY', 'Busy'), ('FAILED', 'Failed'), ('DONE', 'Done')], default='NEW', max_length=15)),
                ('progress', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, null=True)),
                ('eta', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True)),
                ('elapsed', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True)),
                ('error', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('resources', models.ManyToManyField(related_name='session', to='api.youtuberesource')),
            ],
        ),
    ]
