# Generated by Django 4.2.10 on 2024-03-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuberesource',
            name='title',
            field=models.TextField(blank=True, default='N/A', max_length=200, null=True),
        ),
    ]
