# Generated by Django 3.2.15 on 2022-08-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuberesource',
            name='filename',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
