# Generated by Django 3.2.15 on 2022-08-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuberesource',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
