# Generated by Django 3.2.15 on 2022-08-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuberesource',
            old_name='archive',
            new_name='music',
        ),
    ]
