# Generated by Django 3.2.15 on 2022-08-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuberesource',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('QUEUED', 'Queued'), ('BUSY', 'Busy'), ('FAILED', 'Failed'), ('DONE', 'Done'), ('ARCHIVED', 'Archived')], default='NEW', max_length=15),
        ),
    ]
