# Generated by Django 3.2.15 on 2022-08-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_rename_archive_youtuberesource_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuberesource',
            name='youtube_url',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
