# Generated by Django 3.2.15 on 2022-08-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_alter_youtuberesource_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuberesource',
            name='artist',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='youtuberesource',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
