# Generated by Django 3.2.15 on 2022-08-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20220831_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuberesource',
            name='categories',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
