# Generated by Django 3.2.15 on 2022-09-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_youtuberesource_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuberesource',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
