# Generated by Django 3.2.15 on 2022-09-07 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_youtuberesource_needs_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtuberesource',
            name='needs_review',
        ),
    ]
